name: shop_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  http: ^1.1.0
  intl: ^0.18.1

  slide_countdown: ^1.5.2
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  readmore: ^2.2.0

  flutter_timezone: ^1.0.6
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.0
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.1
  fl_country_code_picker: ^0.1.5

  #Icons
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.2

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/img/icon_app_android.png"
  image_path_ios: "assets/img/icon_app_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
